version: "3.1"

services:
  app:
    image: "de22b5fb2d9e70bb4fcc9708470309891f8504709da2d1c6cac2bcdc4230f155"
    container_name: app
    ports:
      - "8090:8090"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_URL=jdbc:postgresql://db:5432/transport_solution
    depends_on:
      - db

  db:
    image: "postgres"
    container_name: db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
