version: "3.1"

services:
  app_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app_db
    volumes:
      - pg_app:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - keycloak_dev_network

  app:
    restart: always
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - app_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app_db:5432/app_db
      - JAVA_OPTS=-Xmx512m
    networks:
      - keycloak_dev_network

volumes:
  pg_app:

networks:
  keycloak_dev_network:
    driver: bridge
